"""Message and validation schemas for constrained LLM communication."""
from datetime import datetime, timezone
from enum import Enum
from typing import List, Dict, Optional, Any
from pydantic import BaseModel, Field
from src.domain.actions import ActionType

DEFAULT_MESSAGE_POLICY_VERSION: str = "msg_v5.0.0"
DEFAULT_VALIDATOR_VERSION: str = "val_v5.0.0"


class MessageValidationStatus(str, Enum):
    """Validation disposition for candidate message."""
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class MessageRejectionReason(str, Enum):
    """Deterministic rejection codes for message validation failures."""
    FAILURE_CODE_MISMATCH = "FAILURE_CODE_MISMATCH"
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    AMOUNT_MISSING = "AMOUNT_MISSING"
    ACTION_MISMATCH = "ACTION_MISMATCH"
    CONSENT_MISSING = "CONSENT_MISSING"
    UNAPPROVED_TEMPLATE = "UNAPPROVED_TEMPLATE"
    REQUIRED_FACT_MISSING = "REQUIRED_FACT_MISSING"
    HALLUCINATED_FACT = "HALLUCINATED_FACT"
    FORBIDDEN_CONTENT = "FORBIDDEN_CONTENT"


class CandidateMessage(BaseModel):
    """Candidate message generated by LLM provider for review."""
    template_id: str
    body_text: str
    stated_amount: Optional[float] = None
    stated_failure_reason: Optional[str] = None
    stated_action: Optional[ActionType] = None
    metadata: Dict[str, Any] = Field(default_factory=dict)


class ValidationResult(BaseModel):
    """Deterministic disposition produced by MessageValidator."""
    is_approved: bool
    status: MessageValidationStatus
    rejection_reasons: List[MessageRejectionReason] = Field(default_factory=list)
    validator_version: str = DEFAULT_VALIDATOR_VERSION
    validated_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class MessageAuditRecord(BaseModel):
    """Immutable audit trail of generated and validated customer messages."""
    message_id: str
    case_id: str
    decision_id: str
    selected_action: ActionType
    template_id: str
    template_version: str
    message_policy_version: str = DEFAULT_MESSAGE_POLICY_VERSION
    generated_message: str
    validation_status: MessageValidationStatus
    rejection_reasons: List[str] = Field(default_factory=list)
    validator_version: str = DEFAULT_VALIDATOR_VERSION
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
